apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: node-update-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-update-controller
  template:
    metadata:
      labels:
        app: node-update-controller
    spec:
      containers:
        - image: kubermatic/node-update-controller:latest
          imagePullPolicy: IfNotPresent
          name: node-update-controller
          command:
            - /usr/local/bin/node-update-controller